app_triangle:
    methods: GET
    path: /triangle/{a}/{b}/{c}
    controller: App\Controller\GeometryController::triangle
app_circle:
    methods: GET
    path: /circle/{radius}
    controller: App\Controller\GeometryController::circle
app_sum:
    methods: GET
    path: /sum
    controller: App\Controller\GeometryController::sum